### ISSUE TITLE
iOS: Swift compiler error. Is not a member type of 'Argyle'

### ISSUE THREAD

**Issue by nikolaydevico** [argyle-systems/argyle-link-sdk-react-native#11]
Hi, I'm getting swift compiler error with details attached on screenshot. All of them are related to `is not a member type of 'Argyle'`

<img width="1420" alt="Screenshot 2020-10-02 at 17 16 02" src="https://user-images.githubusercontent.com/71430571/94933816-963b2080-04d3-11eb-99d7-72d4d69697a7.png">

### Environment:
@argyleio/argyle-plugin-react-native: "^1.5.3"
Xcode: 12.0.1

**Comment by Zujus** [comment]
@nikolaydevico we are looking into it. @Varnius will get back to you soon.

**Comment by Varnius** [comment]
@nikolaydevico Hi. You need to use 5.3.1 version of Swift Compiler. Two options here:
* Upgrade to Xcode 12.2 and it will simply work as required compiler version is bundled with 12.2
* Upgrade to a more recent toolchain but keep in mind that React Native does not respect default toolchain selected in Xcode when building from command line, so you may need to find a way to set it as default (use §swift --version§ to check what’s the default on your system)

**Comment by nikolaydevico** [comment]
@Varnius Thank you, Xcode 12.2 helped to build v1.5.3
But it haven't resolved issue I had on my device, it's related to #9, is there any way you can help me with that?

**Comment by Varnius** [comment]
Resolved with 1.5.4

**Comment by ykeanu** [comment]
### Environment
* Xcode Version 12.2
* "react-native": "0.61.5"
* "react-native-swift": "^1.2.3"
* "@argyleio/argyle-plugin-react-native": "^1.5.10"

### Issue

Hi Argyle team (@Varnius),

We build our app with Xcode Version 12.2 and it looks like the React Native package is not compatible. Following [Argyle documentation](https://argyle.com/docs/argyle-link/react-native-integration), we have done the following steps:
1. `$ yarn add react-native-swift`
2. `$ react-native link react-native-swift` **NOTE: This doesn't do anything**
3. `$ yarn add @argyleio/argyle-plugin-react-native
4. `$ cd ios/ && pod install && pod update``

We are running into these errors on Xcode:
```
error: failed to build module 'Argyle' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'
```

```
'Argyle' is not a member type of 'Argyle'....
```

````
The following build commands failed:
	CompileSwift normal x86_64 /Users/izzykeanu/Dave/react-mobile-app/node_modules/@argyleio/argyle-plugin-react-native/ios/ARArgyleSdk.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

It seems like Argyle compiled with version 5.3 (which is Xcode 12.0) and is not compatible with Xcode 12.2. Does the npm package need to be updated to be compatible with the swift version used in Xcode 12.2?

**Comment by Varnius** [comment]
Hey @ykeanu, you are right - the current version of SDK is compiled using 5.3. We did support pre-release version of 5.3.1 but dropped the support since due it causing problems with older compiler versions. As an answer to (1) - we don't officially support 5.3.1 yet but it's in our near term roadmap. (2) - this is probably not relevant to current versions of RN anymore. We will update the docs.

So, currently compiling with 5.3 should just work. 5.3 is default for Xcode 12.0 and you can switch to it even with Xcode 12.2.

`'Argyle' is not a member type of 'Argyle'` is related to this bug in Swift compiler: https://bugs.swift.org/browse/SR-898?focusedCommentId=12746&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12746
It's quite easy to work it around, by running `find . -name "*.swiftinterface" -exec sed -i -e 's/Argyle\.//g' {} \;`
(https://developer.apple.com/forums/thread/123253?answerId=384974022#384974022)

**Comment by ykeanu** [comment]
@Varnius I attempted the downgrade, but it looks like our application code isn't compatible with an older swift version. When could we anticipate support for swift 5.3.1? Is there an alternative way to integrate the SDK into our app using the most recent Xcode version (12.2)?

**Comment by Varnius** [comment]
@ykeanu Hey. `1.5.11` is coming out tomorrow - it will also include support for Xcode 12.2
